### PR TITLE
fix(pinia-orm): Typings of `useRepo` with Repository are broken

### LINKED ISSUE #1847: Repository typings are broken
### Environment

playground

### Reproduction

https://stackblitz.com/edit/github-t5neyu

### Describe the bug

Problem appeared since version 1.9.0 when using decorators. 1.7.2 worked fine.

### Additional context

_No response_

### Logs

```shell
pages/index.vue:8:26 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(repository: Repository<Model> | Constructor<Repository<Model>>, pinia?: Pinia | undefined): Repository<Model>', gave the following error.
    Argument of type 'typeof UserRepository' is not assignable to parameter of type 'Repository<Model> | Constructor<Repository<Model>>'.
      Type 'typeof UserRepository' is not assignable to type 'Constructor<Repository<Model>>'.
        Construct signature return types 'UserRepository' and 'Repository<Model>' are incompatible.
          The types of 'query().wheres' are incompatible between these types.
            Type 'Where<User>[]' is not assignable to type 'Where<Model>[]'.
              Type 'Where<User>' is not assignable to type 'Where<Model>'.
                Types of property 'field' are incompatible.
                  Type 'string | string[] | WherePrimaryClosure<User> | undefined' is not assignable to type 'string | string[] | WherePrimaryClosure<Model> | undefined'.
                    Type 'WherePrimaryClosure<User>' is not assignable to type 'string | string[] | WherePrimaryClosure<Model> | undefined'.
                      Type 'WherePrimaryClosure<User>' is not assignable to type 'WherePrimaryClosure<Model>'.
                        Type 'Model' is not assignable to type 'User'.
  Overload 2 of 2, '(model: Constructor<Model>, pinia?: Pinia | undefined): Repository<Model>', gave the following error.
    Argument of type 'typeof UserRepository' is not assignable to parameter of type 'Constructor<Model>'.
      Type 'UserRepository' is missing the following properties from type 'Model': _meta, $entity, $config, $namespace, and 39 more.

8 const userRepo = useRepo(UserRepository);
                           ~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by CodeDredd**
### 🔗 Linked issue

closes #1847

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/pinia-orm/src/composables/useRepo.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { Database } from '../database/Database'
 import type { Constructor } from '../types'
 import { registerPlugins } from '../store/Plugins'
 
-export function useRepo<R extends Repository> (
+export function useRepo<R extends Repository<any>> (
```
Comment (daniser) [inline packages/pinia-orm/src/composables/useRepo.ts:8]: I don't get why it stopped working in the first place... Is it somehow related to the attribute autocompletion?
